include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: false
    avoid_redundant_argument_values: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    avoid_positional_boolean_parameters: false